name: Docker Image CI

on:
  push:
    branches: [ generated_files ]
  pull_request:
    branches: [ generated_files ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag privoxy-adb:$(date +%s)
